spring.application.name=APIGateWay


eureka.client.service-url.defaultZone=http://localhost:8761/eureka
server.port=9090

# details of Doctor Microservice
#spring.cloud.gateway.routes[0].id=doctor-microservice
#spring.cloud.gateway.routes[0].uri=http://localhost:8082
#spring.cloud.gateway.routes[0].predicates[0]=Path=/doctor/**

# details of Hospital Microservice
#spring.cloud.gateway.routes[1].id=hospital-microservice
#spring.cloud.gateway.routes[1].uri=http://localhost:8081
#spring.cloud.gateway.routes[1].predicates[0]=Path=/hospital/**

# ==========================
# Book Service
# ==========================
spring.cloud.gateway.routes[0].id=book-microservice
spring.cloud.gateway.routes[0].uri=http://localhost:8040
spring.cloud.gateway.routes[0].predicates[0]=Path=/book/**

# ==========================
# User Service
# ==========================
spring.cloud.gateway.routes[1].id=user-microservice
spring.cloud.gateway.routes[1].uri=http://localhost:8041
spring.cloud.gateway.routes[1].predicates[0]=Path=/user/**

# ==========================
# Borrow Service
# ==========================
spring.cloud.gateway.routes[2].id=borrow-microservice
spring.cloud.gateway.routes[2].uri=http://localhost:8042
spring.cloud.gateway.routes[2].predicates[0]=Path=/borrow/**


